name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 4 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xuwei-k' }}
    steps:
    - uses: actions/setup-java@v5
      with:
        distribution: adopt
        java-version: 11
    - name: Generate token
      id: generate_token
      uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
      with:
        app-id: 89536
        private-key: ${{ secrets.XUWEI_K_BOT_KEY }}
    - name: Launch Scala Steward
      uses: scala-steward-org/scala-steward-action@026472ebc0e1f80577b240b249e3dc1494e7041b # v2.86.0
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74788111+xuwei-k-bot[bot]@users.noreply.github.com"
        author-name: xuwei-k-bot[bot]
