on:
  push:
jobs:
  steward-cache-expire:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xuwei-k' }}
    steps:
    - run: echo "$HOME"
    - uses: actions/cache/restore@v5
      with:
        path: |
          /home/runner/work/scala-steward/workspace
        key: scala-steward-
        restore-keys: |
          scala-steward-
