on:
  push:
jobs:
  steward-cache-expire:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xuwei-k' }}
    steps:
    - uses: actions/cache/restore@v5
      with:
        path: ./tmp
        key: scala-steward-8572f6cf-1777363775340
        restore-keys: |
          Linux-sbt-1.12.8-1.1.6
          sbt-ivy2-cache-test-
          coursier-test-
          scala-steward-
          scala-steward-8572f6cf-1777363775340
